title: Taufiq Islam Protick
theme: jekyll-theme-minimal
description: Hi, I am Taufiq. I am a doctoral student at NC State doing research on natural language processing and usable security and privacy.