title: Taufiq Islam Protick
logo: /assets/images/TaufiqIslamProtick.jpg
theme: jekyll-theme-minimal
description: Hi, I am Taufiq. I am a doctoral student at NC State doing research on natural language processing and usable security and privacy.
